version: '3.7'
services:

  # ---------------------------------------------------------------------------- #
  #                                      API                                     #
  # ---------------------------------------------------------------------------- #

  api:
    container_name: ${SERVICE_NAME}-api
    # restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    build:
      context: .
      dockerfile: Dockerfile.envs
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - database
  
  # ---------------------------------------------------------------------------- #
  #                                   POCKETBASE                                 #
  # ---------------------------------------------------------------------------- #

  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      POCKETBASE_ADMIN_EMAIL: "${POCKETBASE_ADMIN_EMAIL}"
      POCKETBASE_ADMIN_PASSWORD: "${POCKETBASE_ADMIN_PASSWORD}"
    volumes:
      - pocketbase-data:/pb_data
      - ./pocketbase-migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - database
  
networks:
  database:
    driver: bridge
  

volumes:
  pocketbase-data: {}
